language: go

go:
  - "1.10.x"
  - "1.x"
  - master

install:
  - "true"

before_script:
  - GO_FILES=$(find . -iname '*.go' | grep -v /vendor/)  # All the .go files, excluding vendor/ if any
  - PKGS=$(go list ./... | grep -v /vendor/)             # All the import paths, excluding vendor/ if any
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh # Install latest dep release
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - dep ensure -v
  - go build ./...
  - if [ -n "$(gofmt -s -l $GO_FILES)" ]; then echo "gofmt the following files:"; gofmt -s -l $GO_FILES; exit 1; fi
  - go vet ./...
  - go test -v -race $PKGS            # Run all the tests with the race detector enabled
  - megacheck ./...
